export const FETCH_COUNTRY_FILTER = 'FETCH_COUNTRY_FILTER';
export const FETCH_SOURCE_FILTER = 'FETCH_SOURCE_FILTER';
export const FETCH_CATEGORY_FILTER = 'FETCH_CATEGORY_FILTER';
export const FETCH_BRAND_FILTER = 'FETCH_BRAND_FILTER';
export const FETCH_PSKU_DATA = 'FETCH_PSKU_DATA';
export const UPDATE_LIST = 'UPDATE_LIST';
export const UPDATE_PSKU = 'UPDATE_PSKU';
export const UPDATE_LIST_DATA = 'UPDATE_LIST_DATA';
export const FETCH_SOURCE_FILTER_INITIAL = 'FETCH_SOURCE_FILTER_INITIAL';
export const FETCH_CATEGORY_FILTER_INITIAL = 'FETCH_SOURCE_FILTER_INITIAL';
export const FETCH_BRAND_FILTER_INITIAL = 'FETCH_SOURCE_FILTER_INITIAL';
export const UPDATED_FLAG = 'UPDATED_FLAG';
export const UPDATED_FLAG_FALSE = 'UPDATED_FLAG_FALSE';
export const GET_USERNAME = 'GET_USERNAME';


